---
title: 'Assignment #1'
author: "Kim Ting Li"
date: "October 3, 2017"
output:
  pdf_document: default
  html_document: default
---

##4.1.1 #2
```{r}
#Yes, the sequence appear to be converging
fn <- numeric(30)
fn[1] <- fn[2] <- 1
for (i in 3:30) fn[i] <- fn[i-2] + fn[i-1]
c<-numeric(29)
for (j in 2:30) c[j-1]<-(fn[j]/fn[j-1])
print(c) 
```
```{r}
#result for golden ratio
a<-((1+sqrt(5))/2)
a
```
```{r}
# We can show the convergence by plotting the sequence and show 
#it goes towards the horizontal line that's the golden ratio
plot(c)
lines(c,col='red')
abline(h=((1+sqrt(5))/2), col='blue',lty=3)
```

##4.1.1 #3

```{r}
answer <- 0
for (j in 1:5) answer <- answer+j
answer
```

```{r}
answer <- NULL
for(j in 1:5) answer <- c(answer,j)
answer
```

```{r}
answer <- 0
for (j in 1:5) answer<-c(answer,j)
answer
```

```{r}
answer <- 1
for (j in 1:5) answer<-answer*j
answer
```

```{r}
answer <- 3
for (j in 1:15) answer <- c(answer, (7*answer[j])%%31)
answer
```

##4.1.2 #4
```{r}
GICreturn<-function(P,n){
  if(n<=3) return(P*((1+0.04)^n-1))
  else return(P*((1+0.05)^n-1))
}
```

##4.1.2 #5
```{r}
#when it is an open mortgage, put TRUE for the OPEN argument
R<-function(p,n,OPEN){
  if (OPEN==TRUE) i=0.005
  else i=0.004
  R=(p*i/(1-(1+i)^(-n)))
  return (R)
}
```

##4.1.3 #2
```{r}
Fibonacci<-NULL
Fibonacci[1]<-1
Fibonacci[2]<-1
Fibonacci<-c(Fibonacci[1],Fibonacci[2])
while ((Fibonacci[length(Fibonacci)]+Fibonacci[length(Fibonacci)-1])<300) {
  Fibonacci<-c(Fibonacci,(Fibonacci[length(Fibonacci)]+Fibonacci[length(Fibonacci)-1]))
}
print(Fibonacci)

```

##4.1.3 #4
```{r}
i<-0.006
while(i-((1-(1+i)^(-20))/19) >= 0.000001){
  i<-(1-(1+i)^(-20))/19}
print(i)
```

##4.1.3 #5
```{r}
i<-0.006
a<-0
while(i-((1-(1+i)^(-20))/19) >= 0.000001){
  i<-(1-(1+i)^(-20))/19
  a=a+1}
print(a)
print(i)
```

##4.1.5 #2
```{r}
#Results for the original function and the modified function 
#with BREAK statement are listed below, they are the same. 
#Therefore, question b is demonstrated. 
Eratosthenes <- function(n) {
if (n >= 2) {
  sieve <- seq(2, n)
  primes <- c()
  while (length(sieve) > 0) {
    p <- sieve[1]
    primes <- c(primes, p)
    sieve <- sieve[(sieve %% p) != 0]
  }
return(primes)
} else {
stop
}
}
Eratosthenes(200)
```
```{r}
ModifiedE <- function(n) {
if (n >= 2) {
  sieve <- seq(2, n)
  primes <- c()
  while (length(sieve) > 0) {
    p <- sieve[1]
    if (p>=sqrt(n)) break
    primes <- c(primes, p)
    sieve <- sieve[(sieve %% p) != 0]
    
  }
  primes<-c(primes, sieve)
return(primes)
} else {
stop
}
}
ModifiedE(200)

Eratosthenes(200)==ModifiedE(200)
```

##4.2.1 #2
```{r}
compound.interest<-function(P,ir,n){
  x<-(P*(1+ir)^n)
  return(x)
}
compound.interest(1000,0.01,30)
```

##4.2.1 #3
```{r}
#to give an answer for the precision of 6 decimal places
bisection<-function(f,x1,x2){
  repeat{
  f1<-f(x1)
  f2<-f(x2)
  x3<-(x1+x2)/2
  f3<-f(x3)
  if (f3==0){
    print(x3) 
    break
  }
  else {
    if (f3*f1<0){
      x1<-x3
    } else{
      x2<-x3
    }
  }
  if (abs(x1-x2)<0.000001){
    print((x1+x2)/2) 
    break
  }
  }
}

```

##4.4.1 #1
```{r}
mergesort <- function (x,decreasing) {
  if (decreasing==TRUE){
  len <-length(x)
  if (len < 2) result <- x
  else {
    y <- x[1:(len / 2)]
    z <- x[(len / 2 + 1):len]
    y <- mergesort(y,TRUE)
    z <- mergesort(z,TRUE)
    result<-c()
      while(min(length(y), length(z)) > 0){
        if(y[1]>z[1]){
          result<-c(result,y[1])
          y<-y[-1]
        } else{
          result<-c(result,z[1])
          z<-z[-1]
        }
          
      }
      if (length(y) > 0){
        result <- c(result, y)
      } else {
        result <- c(result, z)
      }
     
    }
  }else{
    len <-length(x)
  if (len < 2) result <- x
  else {
    y <- x[1:(len / 2)]
    z <- x[(len / 2 + 1):len]
    y <- mergesort(y,FALSE)
    z <- mergesort(z,FALSE)
    result<-c()
      while(min(length(y), length(z)) > 0){
        if(y[1]<z[1]){
          result<-c(result,y[1])
          y<-y[-1]
        } else{
          result<-c(result,z[1])
          z<-z[-1]
        }
          
      }
      if (length(y) > 0){
        result <- c(result, y)
      } else {
        result <- c(result, z)
      }
     
    }
}
return(result)
    
}

a<-c(2,5,1,6,7,11,8,10)
b<-c(2,5,1,6,7,11,8,10)
mergesort(a,TRUE)
mergesort(b,FALSE)

```

##4.4.1 #2 !!!!!
```{r}
  f<-function(x,y) (x+y)
  g<-function(x,y) (x^2+2*y^2-2)

answer<-function(f,g,x,y){

  dfx<-function(x,y){}
  dfy<-function(x,y){}
  dgx<-function(x,y){}
  dgy<-function(x,y){}
  
  body(dfx)=D(body(f),'x')
  body(dfy)=D(body(f),'y')
  body(dgx)=D(body(g),'x')
  body(dgy)=D(body(g),'y')
  
  tolerance<-0.000001
  
  while (f(x,y) > tolerance){
    x <- x-(dgy(x,y)*f(x,y)-dfy(x,y)*g(x,y))/(dfx(x,y)*dgy(x,y)-dfy(x,y)*dgx(x,y))
    y <- y-(dfx(x,y)*g(x,y)-dgx(x,y)*f(x,y))/(dfx(x,y)*dgy(x,y)-dfy(x,y)*dgx(x,y))
  }
  print(x)
  print(y)
}

answer(f,g,100,100)
```

##Chapter 4 #1
```{r}
directpoly<-function(x,c){
   p<-0
    for(a in 1:length(c)){
    p1<-(c[a]*x^(a-1))
    p=p+p1
  }
  return(p)
}

directpoly(2,c(4,6,2,9))

directpoly(c(2,5),c(4,6,2,9))
```

##Chapter 4 #2
```{r}
hornerpoly<-function(x,c){
  p<-0
  a<-matrix(0,length(x),length(c))
  a[,length(c)]<-c[length(c)]
  for (i in (length(c)-1):1){
    a[,i]<-a[,i+1]*x+c[i]
  }
  return(a[,1])
}
hornerpoly(2,c(4,6,2,9))

hornerpoly(c(2,5),c(4,6,2,9))
```

##Chapter 4 #3
```{r}
system.time(directpoly(x=seq(-10,10,length=5000000),c(1,-2,2,3,4,6,7)))

system.time(hornerpoly(x=seq(-10,10,length=5000000),c(1,-2,2,3,4,6,7)))

#the first algorithm is slower in user time and elapsed time, 
#but the system time is similar. 
```

```{r}
system.time(directpoly(x=seq(-10,10,length=5000000),c(2,17,-3)))

system.time(hornerpoly(x=seq(-10,10,length=5000000),c(2,17,-3)))

#when the number of coefficients is smaller, it takes less time to execute
#the code in general. The two algorithms also run at very similar speed 
#when the number of coefficient is small.
```

